// packages/examples/vue3-demo-esm/css-modules/src/App.vue
<template>
  <div>
    <h3>css-modules Remote App</h3>
    <Button />
  </div>
</template>

<script>
import { ref} from "vue";
import Button from "./components/Button.vue";
export default {
  components: {
    Button,
  },
  setup() {
    const count = ref(0);
    const inc = () => {
      count.value++;
    };

    return {
      count,
      inc,
    };
  },
};
</script>

// packages/examples/react-advanced/remote/src/App.jsx
import './App.css'
import useBearStore from "./state/useBearStore";
import Button from "./components/Button";

function App() {
  const bears = useBearStore((state) => state.bears)

  return (
    <div className="App">
      <h1>{bears} around here ...</h1>
      <Button/>
    </div>
  )
}

export default App
